# Site settings
title: Emily Errington Doula Services
subtitle: Wildflower Doula Co.
email: doula@emilyerrington.com
description: Emily Errington Doula Services - helping moms with their babies. Certified DONA Doula in the Lubbock, TX area.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://emilyerrington.com" # the base hostname & protocol for your site
author: Emily Errington
street_address: 
city: Lubbock
state: TX
zip_code: 
country: United States of America
author:
  name   : "Emily Errington"

# Social settings
500px_url:
facebook_url: https://www.facebook.com/doula.emilyerr
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/doula.emilyerr
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

permalink: /:categories/:title/

sass:
  sass_dir: _sass
  style: compressed

plugins: 
  - jekyll-sitemap
  - jekyll-seo-tag