- title: Emotional Support
  img: fa-heart
  desc : "As a doula I help families feel supported by making the emotional side of labor as easy and calm as possible. When you're at ease your hormones can work with your body helping your baby arrive safely. Whether a birth is unmedicated or interventions are needed, all families can benefit from having a doula on their birth team. "

- title: Physical Support
  img: fa-thumbs-up
  desc : "Not only am I trained as a birth doula, but I have also trained through the Spinning Babies program. This has given me many position ideas for comfort and labor progression. This includes hands on techniques like counter pressures, as well as positional changes that can help a baby move into the birth canal and through the pelvis without strenuous interventions."
  
- title: Support for your partner
  img: fa-user
  desc: "Whether it's your husband, mom, sister, or friend, I support them so they can in turn support you! Often times the person you choose to be with you during your labor is the person that knows you best! They make a great support person for you. I help teach them and guide them to be as involved in the labor as you choose."

- title: Informational Support
  img: fa-info-circle
  desc: "As a DONA International certified doula, I can help show you evidence-based birth resources so that you can be informed and ask the questions that you need answered. When you are well informed you will be able to better advocate for yourself so you can have the best birth possible for you and your baby."